### ISSUE TITLE
Feature branch commits cause unwanted pushes

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/distribution-updater#2]
@dstillman, I just noticed that feature branch commits on https://github.com/citation-style-language/styles seem to be pushed to the "master" branch of the https://github.com/citation-style-language/styles-distribution repo. This is bad. Only commits to "master" should trigger a push.

See e.g. https://github.com/citation-style-language/styles/commit/45503dc0655a16133925335457490682e27116e9 (feature branch "travis-changes") which caused https://github.com/citation-style-language/styles-distribution/commit/22df00eb507a510561610fd77e1748f13dd35a00

(cc @adam3smith)

**Comment by rmzelle** [comment]
I guess one quick way to fix this is by limiting the Travis builds to "master" by whitelisting it in .travis.yml (per https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches ), although I find the feature branch Travis builds rather useful.

**Comment by dstillman** [comment]
Hmm, I thought we fixed this...

**Comment by rmzelle** [comment]
Last time we were having issues with PRs: https://github.com/citation-style-language/distribution-updater/commit/861cb537d18a261175da04968f207a01de7b25a6

I wonder if the Travis payload mentions the branch.

**Comment by rmzelle** [comment]
> I wonder if the Travis payload mentions the branch.

Looks like it does: https://docs.travis-ci.com/user/notifications/#Webhooks-Delivery-Format (`"branch": "master"`)

Could we then just use (new lines indicated with "+"):

```
    if request_body:
        try:
            payload = json.loads(parse_qs(request_body)["payload"][0])
            environ["type"] = payload["type"]
            environ["commit_hash"] = payload["commit"]
            environ["build_status"] = payload["status"]
+           environ["branch"] = payload["branch"]

...

def update_styles(environ):
    if (environ["response_status"][0:3] != "200"
            or environ["build_status"] != 0
+           or environ["branch"] != "master"
            or environ["type"] == "pull_request"):
        return
```

**Comment by dstillman** [comment]
Yup. That's done — if you want to trigger a feature branch commit, we can make sure it works, and then I'll commit it.

**Comment by rmzelle** [comment]
https://travis-ci.org/citation-style-language/styles/builds/111580613

**Comment by rmzelle** [comment]
Awesome, thanks.

https://www.zotero.org/styles?q=augmented doesn't yet show https://github.com/citation-style-language/styles-distribution/blob/master/dependent/augmented-human-research.csl from two hours ago, though. Is that plumbing all working?

**Comment by dstillman** [comment]
Oops, wasn't working. Should be fixed now, with the page updating within a few seconds of commits — thanks.

**Comment by rmzelle** [comment]
My commit from just now went indeed live on zotero.org/styles right away. Thanks for that too!

**Comment by rmzelle** [comment]
@dstillman, sorry to bug you, but https://github.com/citation-style-language/styles-distribution/commit/8681c7b16274c16b4ed63528b572a6ee81a4181a hasn't made it to the ZSR yet. (see https://www.zotero.org/styles?q=clara)

This should have happened already, right? It's been over an hour.

**Comment by rmzelle** [comment]
(it's online now)
